### ISSUE TITLE
Occasional momentary lag / freeze whenever I save.

### ISSUE THREAD

**Issue by hitchhiker** [yysun/Git-Source-Control-Provider#8]
Great tool but it tends to cause VS2010 to freeze up for a second or two _mainly_ when I save a file. I have a very large project, thousands of files. Perhaps something could be offloaded to a background thread? I haven't tested to be 100% sure that GSCP is causing this issue. I also have resharper installed, no other plugins though. When I disable R# I see no benefit, when I disable GSCP I do.

Cheers,
Frank.

**Comment by hitchhiker** [comment]
Yeah, it's 2 weeks later, I'm having to disable it while I work and enable it when i need it.

**Comment by aarondl** [comment]
I'm also seeing this issue. When I looked into it it seems like the problem is that the plugin is updating the glyphs on all files in the project on every save of any file. GitSharp is also a culprit as it's doing file comparisons in what seems to be to be an inefficient manner (exhaustive content compare versus immediately dismissing them as dissimilar based on a simple length check). I'm going to see what I can do about this once I get some spare time.

**Comment by hitchhiker** [comment]
Cheers, it's a nightmare on projects with 10,000s of files.

**Comment by aarondl** [comment]
I felt it'd be prudent to say that I looked into this and decided against fixing it. Just letting you know not to hold your breath!

**Comment by hitchhiker** [comment]
Thanks for the heads-up - I'm sure there's a good reason.
Cheers,
Frank.

**Comment by bachbui** [comment]
Is it possible to re-open this issue? I'm seeing the same problem, even with a more modestly sized solution (9 projects, maybe a couple hundred files). Even if it won't be addressed for a while, it would make sense to leave it as a pending issue.

**Comment by Miraculix** [comment]
Since I'm experiencing this issue as well and want to stick to GitSCP I decided to have a look myself.
I pretty much nailed down the issue and working on a fix now. After all it's not that hard to fix that Issue.
I'll let you know when the fix is available

**Comment by bachbui** [comment]
Thank you, kind sir.
